# Telegram Bot Kimliği (BotFather'dan aldığın token'ı buraya yapıştır)
#deneme kanalı
 # //var botToken = "8869455219:AAEO_h33-FMgs79R55QGIHriY8cx7qUieOk";
 # //var chatId = "-1003683404801";
TELEGRAM_TOKEN = "8869455219:AAEO_h33-FMgs79R55QGIHriY8cx7qUieOk"

# Öncelikli Taranacak Hisseler (Hızlı Tarama) - Yahoo formatında (.IS uzantılı)
BIST100 = [
    "AEFES.IS", "AGHOL.IS", "AKBNK.IS", "AKCNS.IS", "AKFGY.IS", "AKSA.IS", "AKSEN.IS", "ALARK.IS", "ALBRK.IS", "ALFAS.IS",
    "ALTNY.IS", "ANGGEN.IS", "ANSGR.IS", "ARCLK.IS", "ASELS.IS", "ASTOR.IS", "ASUZU.IS", "AYDEM.IS", "BAGFAS.IS", "BALSU.IS",
    "BERA.IS", "BIMAS.IS", "BIOEN.IS", "BOBET.IS", "BRSAN.IS", "BRYAT.IS", "BTCIM.IS", "BUCIM.IS", "CANTE.IS", "CCOLA.IS",
    "CIMSA.IS", "CWENE.IS", "DOAS.IS", "DOHOL.IS", "ECILC.IS", "ECZYT.IS", "EGEEN.IS", "EKGYO.IS", "ENJSA.IS", "ENKAI.IS",
    "EREGL.IS", "EUPWR.IS", "FROTO.IS", "GARAN.IS", "GESAN.IS", "GSDHO.IS", "GUBRF.IS", "GWIND.IS", "HALKB.IS", "HEKTS.IS",
    "IPEKE.IS", "ISCTR.IS", "ISGYO.IS", "ISMEN.IS", "IZMDC.IS", "KARDMD.IS", "KCHOL.IS", "KCAER.IS", "KENT.IS", "KONTR.IS",
    "KORDS.IS", "KOZAA.IS", "KOZAL.IS", "KPOWR.IS", "MAVI.IS", "MGROS.IS", "MIATK.IS", "NETAS.IS", "ODAS.IS", "OTKAR.IS",
    "OYAKC.IS", "PEKGY.IS", "PETKM.IS", "PGSUS.IS", "PTT.IS", "QUAGR.IS", "REEDR.IS", "SAHOL.IS", "SASA.IS", "SDTTR.IS",
    "SISE.IS", "SKBNK.IS", "SMART.IS", "SOKM.IS", "TABGD.IS", "TCELL.IS", "TEKFEN.IS", "THYAO.IS", "TMSN.IS", "TOASO.IS",
    "TRGYO.IS", "TSKB.IS", "TTKOM.IS", "TTRAK.IS", "TUPRS.IS", "TURSG.IS", "ULKER.IS", "VAKBN.IS", "VESBE.IS", "YKBNK.IS"

    # Not: Listeyi uzatmamak için 10 tane yazdım. BIST 100'ün geri kalanını senin buraya eklemen gerekecek.
]

# Arka Planda Yavaş Taranacak Sığ/Yan Tahtalar
BIST_OTHERS = [
    "A1CAP.IS", "A1YEN.IS", "AAGYO.IS", "ACSEL.IS", "ADEL.IS", "ADESE.IS", "ADGYO.IS", "AFYON.IS", "AGESA.IS", "AGROT.IS",
    "AHGAZ.IS", "AHSGY", "AKENR.IS", "AKFIS.IS", "AKFYE.IS", "AKGRT.IS", "AKHAN.IS", "AKSGY.IS", "AKSUE.IS", "ALCAR.IS",
    "ALCTL.IS", "ALKA.IS", "ALKIM.IS", "ALKLC.IS", "ALVES.IS", "ANELE.IS", "ANGEN.IS", "ANHYT.IS", "ARASE.IS", "ARDYZ.IS",
    "ARENA.IS", "ARFYE.IS", "ARSAN.IS", "ARTMS.IS", "ASCEG.IS", "ATAGY.IS", "ATAKP.IS", "ATATP.IS", "ATEKS.IS", "ATLAS.IS",
    "ATSYH.IS", "AVGYO.IS", "AVHOL.IS", "AVOD.IS", "AVTUR.IS", "AYCES.IS", "AYEN.IS", "AYES.IS", "AYGAZ.IS", "AZTEK.IS",
    "BANVIT.IS", "BARMA.IS", "BAYRK.IS", "BEGYO.IS", "BEYAZ.IS", "BFREN.IS", "BIENY.IS", "BIGCH.IS", "BINGV.IS", "BIZIM.IS",
    "BJKAS.IS", "BLCYT.IS", "BMSCH.IS", "BMSTL.IS", "BNTAS.IS", "BOSSA.IS", "BRKO.IS", "BRKSN.IS", "BRMEN.IS", "BRKVY.IS",
    "BRLSM.IS", "BSOKE.IS", "BTCIM.IS", "BURCE.IS", "BURVA.IS", "BVSAN.IS", "BYDNR.IS", "CASA.IS", "CATES.IS", "CELHA.IS",
    "CEMAS.IS", "CEMTS.IS", "CEOEM.IS", "CIMSA.IS", "CLEBI.IS", "CMBTN.IS", "CMENT.IS", "CONSE.IS", "COSMO.IS", "CRDFA.IS",
    "CRFSA.IS", "CUSAN.IS", "CVKMD.IS", "DAGHL.IS", "DAGI.IS", "DAPGM.IS", "DARDL.IS", "DATAG.IS", "DENTS.IS", "DERIM.IS",
    "DESA.IS", "DESPC.IS", "DEVA.IS", "DGATE.IS", "DGGYO.IS", "DGNMO.IS", "DIRIT.IS", "DITAS.IS", "DMSAS.IS", "DNISI.IS",
    "DOCO.IS", "DOGUB.IS", "DOHOL.IS", "DOKTA.IS", "DURDO.IS", "DYOBY.IS", "DZGYO.IS", "EDATA.IS", "EDIP.IS", "EFORG.IS",
    "EGCYH.IS", "EGEPO.IS", "EGGUB.IS", "EGPRO.IS", "EGSER.IS", "EKIZ.IS", "EKOS.IS", "EKTAM.IS", "ELITE.IS", "EMKEL.IS",
    "EMNIS.IS", "ENTRA.IS", "EPLAS.IS", "ERBOS.IS", "ERCB.IS", "ERSU.IS", "ESCAR.IS", "ESCOM.IS", "ESEN.IS", "ETILR.IS",
    "ETYAT.IS", "EUHOL.IS", "EUKYO.IS", "EUREN.IS", "EUYO.IS", "EYGYO.IS", "FADE.IS", "FENER.IS", "FLAP.IS", "FMIZP.IS",
    "FONET.IS", "FRIGO.IS", "FORMT.IS", "FORTE.IS", "FZLGY.IS", "GALAT.IS", "GENTS.IS", "GEREL.IS", "GIPTA.IS", "GLBMD.IS",
    "GLCVY.IS", "GLRYH.IS", "GLYHO.IS", "GMTN.IS", "GOODY.IS", "GOZDE.IS", "GRNYO.IS", "GRSEL.IS", "GSRAY.IS", "GUBRF.IS",
    "GZNMI.IS", "HATEK.IS", "HATSN.IS", "HDFGS.IS", "HEDEF.IS", "HHLDG.IS", "HOROZ.IS", "HUBVC.IS", "HUNER.IS", "HURGZ.IS",
    "ICBCT.IS", "IEHOH.IS", "IHAAS.IS", "IHEVA.IS", "IHGZT.IS", "IHLAS.IS", "IHLGM.IS", "IHYAY.IS", "IMASM.IS", "INDES.IS",
    "INFO.IS", "INGRM.IS", "INTEM.IS", "INVEO.IS", "INVES.IS", "ISKPL.IS", "ISMEN.IS", "ISSEN.IS", "ISYAT.IS", "ITTFH.IS",
    "IZENR.IS", "IZFAS.IS", "JANTS.IS", "KAFEG.IS", "KAPLM.IS", "KARKN.IS", "KARSN.IS", "KARYA.IS", "KATMR.IS", "KAYSE.IS",
    "KBUTG.IS", "KFEIN.IS", "KHONR.IS", "KIMMR.IS", "KIRST.IS", "KLGYO.IS", "KLMSN.IS", "KLNMA.IS", "KLRHO.IS", "KLSER.IS",
    "KLYFT.IS", "KLYTE.IS", "KMELE.IS", "KMPUR.IS", "KNFRT.IS", "KOCMT.IS", "KONKA.IS", "KOPOL.IS", "KOTON.IS", "KRALS.IS",
    "KRGYO.IS", "KRONT.IS", "KRPLS.IS", "KRSTL.IS", "KRTEK.IS", "KRVGD.IS", "KSTUR.IS", "KTLEV.IS", "KUTPO.IS", "KUYAS.IS",
    "KSTUR.IS", "LIDER.IS", "LIDFA.IS", "LILAK.IS", "LINK.IS", "LKMNH.IS", "LMKDC.IS", "LOGAN.IS", "LUKSK.IS", "MACKO.IS",
    "MAGEN.IS", "MAKIM.IS", "MAKTK.IS", "MANAS.IS", "MARKA.IS", "MARTI.IS", "MARGY.IS", "MBMRK.IS", "MDFRM.IS", "MEGAP.IS",
    "MEGMT.IS", "MEPET.IS", "MERCN.IS", "MERKO.IS", "METUR.IS", "METRO.IS", "MHRGY.IS", "MIPAZ.IS", "MMCAS.IS", "MNDRS.IS",
    "MNDTR.IS", "MOBTL.IS", "MOGAN.IS", "MPARK.IS", "MRGYO.IS", "MRSHL.IS", "MSGYO.IS", "MTRKS.IS", "MTRYO.IS", "MZHLD.IS",
    "NIBAS.IS", "NMSGR.IS", "NATEN.IS", "NETAS.IS", "NUGYO.IS", "NUHCM.IS", "OBAMS.IS", "OBASE.IS", "OFSYM.IS", "ONCSM.IS",
    "ORCAE.IS", "ORGE.IS", "ORMA.IS", "OSMEN.IS", "OSTIM.IS", "OYYAT.IS", "OZSUB.IS", "OZGYO.IS", "OZKGY.IS", "PAGYO.IS",
    "PAMEL.IS", "PAPIL.IS", "PARSN.IS", "PASEU.IS", "PATTR.IS", "PCILT.IS", "PEGYO.IS", "PENGD.IS", "PENTA.IS", "PINSU.IS",
    "PKENT.IS", "PKMRK.IS", "PLTUR.IS", "PNLSN.IS", "PNSUT.IS", "POLHO.IS", "POLTK.IS", "PRDGS.IS", "PRKAB.IS", "PRKME.IS",
    "PRZMA.IS", "PSDTC.IS", "QNBFB.IS", "QNBFL.IS", "RALYI.IS", "RNPOL.IS", "RODRG.IS", "ROYAL.IS", "RSTAL.IS", "RTALB.IS",
    "RUZYE.IS", "RYGYO.IS", "RYSAS.IS", "SAFKR.IS", "SAMAT.IS", "SANEL.IS", "SANFM.IS", "SANKO.IS", "SARKY.IS", "SAYAS.IS",
    "SEKFK.IS", "SEKUR.IS", "SELEC.IS", "SELVA.IS", "SEYKM.IS", "SILVR.IS", "SINKO.IS", "SKTAS.IS", "SKYMD.IS", "SMART.IS",
    "SNDRS.IS", "SNGYO.IS", "SNICA.IS", "SNKRN.IS", "SNPAM.IS", "SODSN.IS", "SONME.IS", "SRVGY.IS", "SUMAS.IS", "SUNTK.IS",
    "SURGY.IS", "SUWEN.IS", "TARKM.IS", "TATGD.IS", "TAVHL.IS", "TBORG.IS", "TDGYO.IS", "TEKTU.IS", "TETMT.IS", "TEZOL.IS",
    "TGSAS.IS", "TLMAN.IS", "TMPOL.IS", "TNPAN.IS", "TNZTP.IS", "TRCAS.IS", "TRILC.IS", "TSGYO.IS", "TUCLK.IS", "TUKAS.IS",
    "TUMAS.IS", "TURGG.IS", "TUREX.IS", "UTPYA.IS", "UZERB.IS", "VAKFN.IS", "VAKKO.IS", "VANGD.IS", "VBTYZ.IS", "VERTU.IS",
    "VERUS.IS", "YESIL.IS", "YGGYO.IS", "YGYO.IS", "YAYLA.IS", "YBTAS.IS", "YONGA.IS", "YOTK.IS", "YUNSA.IS", "ZEDUR.IS",
 # BIST TÜM Endeksinden BIST 500 Çıkarılarak Elde Edilen Küçük ve Mikro Ölçekli Hisse Listesi
    "ALMAD.IS", "ALTIN.IS", "APRE.IS", "ARTI.IS", "AYDEM.IS", "BALAT.IS", "BAKAB.IS", "BAMBI.IS", "BEYAZ.IS", 
    "BRKO.IS", "BRMEN.IS", "BURCE.IS", "BURVA.IS", "CASA.IS", "COSMO.IS", "CRDFA.IS", "DAGHL.IS", "DIRIT.IS", 
    "DITAS.IS", "EGCYH.IS", "EKIZ.IS", "EMNIS.IS", "EPY.IS", "ETILR.IS", "ETYAT.IS", "EUHOL.IS", "EUKYO.IS", 
    "EUYO.IS", "FLAP.IS", "FRIGO.IS", "FORMT.IS", "GIPTA.IS", "GLBMD.IS", "GRNYO.IS", "GZNMI.IS", "HATEK.IS", 
    "HDFGS.IS", "HUBVC.IS", "IHAAS.IS", "IHEVA.IS", "IHGZT.IS", "IHLAS.IS", "IHLGM.IS", "IHYAY.IS", "INTEM.IS", 
    "ISBTR.IS", "ISATR.IS", "ISKUR.IS", "KAPLM.IS", "KATMR.IS", "KENT.IS", "KIRST.IS", "KRALS.IS", "KRONT.IS", 
    "KRSTL.IS", "KRTEK.IS", "KSTUR.IS", "KUYAS.IS", "LINK.IS", "LUKSK.IS", "MANAS.IS", "MARKA.IS", "MARTI.IS", 
    "MEGAP.IS", "MEPET.IS", "MERKO.IS", "METUR.IS", "METRO.IS", "MMCAS.IS", "MTRYO.IS", "MZHLD.IS", "NIBAS.IS", 
    "ONCSM.IS", "ORMA.IS", "OSTIM.IS", "OZSUB.IS", "PAGYO.IS", "PAPIL.IS", "PEGYO.IS", "PINSU.IS", "PKENT.IS", 
    "PRDGS.IS", "PRZMA.IS", "QNBFL.IS", "RODRG.IS", "ROYAL.IS", "RTALB.IS", "SAMAT.IS", "SANEL.IS", "SANFM.IS", 
    "SEKUR.IS", "SEYKM.IS", "SILVR.IS", "SINKO.IS", "SNKRN.IS", "SNPAM.IS", "SODSN.IS", "SONME.IS", "SUMAS.IS", 
    "TEKTU.IS", "TETMT.IS", "TGSAS.IS", "TMPOL.IS", "TUCLK.IS", "TUMAS.IS", "TURGG.IS", "UTPYA.IS", "UZERB.IS", 
    "VANGD.IS", "YESIL.IS", "YGYO.IS", "YAYLA.IS", "YBTAS.IS", "YONGA.IS"

]

# J Formasyonu Parametreleri (Buradan kolayca müdahale edebilmen için dışarı aldım)
PARAMS = {
    "kavis_min_dusus_orani": 0.03,  # %3 düşüş şartı
    "hacim_carpani": 1.5,           # 1.5 kat hacim şartı
    "sig_tahta_ciro_siniri": 50_000_000 # 50 Milyon TL ciro sınırı
}
